### ISSUE TITLE
Can we get some styles similar to your docs?

### ISSUE THREAD

**Issue by anuchin** [primary-theme/obsidian#254] opened 2024-10-08 05:03 UTC
### Primary Theme Version

2.10.0

### Debug Info

none 

### Describe the enhancement

Hi, Loving the theme so far. Is there anyway to add lines between the numbers to the steps list you like in your docs?
Also how to change the callouts to be similar to yours on the docs? I think its prettier  :)
![image](https://github.com/user-attachments/assets/affc18db-1052-4ed0-8a82-648eecc47d34)

**Comment by ceciliamay** [comment] 2024-10-08 06:16
hi there! thanks for the kind words 💛 i'm glad you're enjoying it!

for the lines between the numbers, obsidian and the community calls it indentation guides. it's a feature you can toggle on/off through obsidian's settings menu.

To toggle it on, open up settings in obsidian, and go to the **Editor** tab. Under the **Display** section, look for **Show indentation guides**. Toggle it on, and you should be good to go!

The indentation lines will show up in both numbered or bulleted lists.

For the callouts, I'm planning to add different styling options for Callouts through Style Settings in the coming beta update, including one similar to the doc's version. It'll probably be release in mid October in beta (through my [Ko-fi page](https://ko-fi.com/ceciliamay)), and around end of October for public. 

I will now close this because its going to be a duplicate of the Callouts Customization suggestion but I will add this thread as reference!

**Comment by anuchin** [comment] 2024-10-08 06:16
i got the callout using some custom CSS snippets

![image](https://github.com/user-attachments/assets/37b82ec2-5c32-47ef-834c-06f1348c0181)

**Closed as completed by ceciliamay** 2024-10-08 06:16 UTC
Labels: 🧞‍♂️ enhancement

**Comment by holiq** [comment] 2024-11-12 12:29
hi @ceciliamay, how to open settings on tabs (not modal) like on your docs?
![Screenshot from 2024-11-12 19-18-34](https://github.com/user-attachments/assets/8c11f2de-3a96-47d6-97dc-4c47280b300d)
